"""drive document changes

Revision ID: 16c8f62c96ae
Revises: f7e8d9c0b1a2
Create Date: 2026-03-29 10:31:04.160868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '16c8f62c96ae'
down_revision: Union[str, Sequence[str], None] = 'f7e8d9c0b1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _cleanup_stale_batch_tables() -> None:
    # If a previous migration run failed mid-batch, sqlite temp tables may remain.
    for table_name in (
        "_alembic_tmp_compliance_records",
        "_alembic_tmp_guideline_sections",
        "_alembic_tmp_contracts",
    ):
        op.execute(f"DROP TABLE IF EXISTS {table_name}")


def _has_unique_constraint(table_name: str, constraint_name: str) -> bool:
    conn = op.get_bind()
    for constraint in inspect(conn).get_unique_constraints(table_name):
        if constraint.get("name") == constraint_name:
            return True
    return False


def _drop_guideline_views() -> None:
    op.execute("DROP VIEW IF EXISTS v_guideline_section_index")
    op.execute("DROP VIEW IF EXISTS v_guideline_catalog")


def _create_guideline_section_view() -> None:
    op.execute(
        """
        CREATE VIEW v_guideline_section_index AS
        SELECT
            f.id AS framework_id,
            f.slug AS framework_slug,
            f.title AS framework_title,
            s.id AS section_id,
            s.section_key,
            s.title AS section_title,
            s.sort_order
        FROM guideline_sections s
        JOIN guideline_frameworks f ON f.id = s.framework_id
        """
    )


def _create_guideline_views() -> None:
    _create_guideline_section_view()
    op.execute(
        """
        CREATE VIEW v_guideline_catalog AS
        SELECT
            e.id AS catalog_entry_id,
            f.slug AS framework_slug,
            e.bucket,
            e.domain,
            e.code,
            e.sort_order
        FROM guideline_catalog_entries e
        JOIN guideline_frameworks f ON f.id = e.framework_id
        """
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_guideline_views()
    _cleanup_stale_batch_tables()
    # Skip all ALTER operations on a fresh DB — the other migration branch
    # creates all tables with the correct schema already.
    if not inspect(op.get_bind()).has_table('contracts'):
        _create_guideline_views()
        return
    with op.batch_alter_table('compliance_records') as batch_op:
        batch_op.alter_column(
            'contract_id',
            existing_type=sa.INTEGER(),
            nullable=True,
        )
        batch_op.alter_column(
            'check_name',
            existing_type=sa.VARCHAR(),
            nullable=True,
        )
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(),
            nullable=True,
        )
        # SQLite cannot reliably drop unnamed constraints in batch mode.
        # Keep the existing FK definition, which remains valid after nullability changes.

    with op.batch_alter_table('contracts') as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=32),
            type_=sa.Enum(
                'DRAFT',
                'REVIEW',
                'REDRAFT',
                'SIGNING',
                'ACTIVE',
                'APPROVED',
                'EXPIRED',
                'TERMINATED',
                name='contractstatus'
            ),
            nullable=True,
            existing_server_default=sa.text("'draft'"),
        )
    op.drop_index(op.f('ix_gce_framework_bucket'), table_name='guideline_catalog_entries')
    op.create_index(op.f('ix_guideline_catalog_entries_bucket'), 'guideline_catalog_entries', ['bucket'], unique=False)
    op.create_index(op.f('ix_guideline_catalog_entries_domain'), 'guideline_catalog_entries', ['domain'], unique=False)
    op.create_index(op.f('ix_guideline_catalog_entries_id'), 'guideline_catalog_entries', ['id'], unique=False)
    op.create_index(op.f('ix_guideline_frameworks_id'), 'guideline_frameworks', ['id'], unique=False)
    with op.batch_alter_table('guideline_sections') as batch_op:
        batch_op.drop_index(op.f('ix_guideline_sections_framework_id'))
        if _has_unique_constraint('guideline_sections', 'uq_guideline_section_framework_key'):
            batch_op.drop_constraint('uq_guideline_section_framework_key', type_='unique')
        if not _has_unique_constraint('guideline_sections', 'uq_guideline_section_framework_key'):
            batch_op.create_unique_constraint(
                'uq_guideline_section_framework_key',
                ['framework_id', 'section_key']
            )
        batch_op.create_index(op.f('ix_guideline_sections_id'), ['id'], unique=False)
    _create_guideline_views()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_guideline_views()
    _cleanup_stale_batch_tables()
    op.drop_index(op.f('ix_guideline_sections_id'), table_name='guideline_sections')
    op.drop_index(op.f('ix_guideline_frameworks_id'), table_name='guideline_frameworks')
    op.drop_index(op.f('ix_guideline_catalog_entries_id'), table_name='guideline_catalog_entries')
    op.drop_index(op.f('ix_guideline_catalog_entries_domain'), table_name='guideline_catalog_entries')
    op.drop_index(op.f('ix_guideline_catalog_entries_bucket'), table_name='guideline_catalog_entries')
    op.create_index(op.f('ix_gce_framework_bucket'), 'guideline_catalog_entries', ['framework_id', 'bucket'], unique=False)
    with op.batch_alter_table('contracts') as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.Enum(
                'DRAFT',
                'REVIEW',
                'REDRAFT',
                'SIGNING',
                'ACTIVE',
                'APPROVED',
                'EXPIRED',
                'TERMINATED',
                name='contractstatus'
            ),
            type_=sa.VARCHAR(length=32),
            nullable=False,
            existing_server_default=sa.text("'draft'"),
        )
    with op.batch_alter_table('compliance_records') as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(),
            nullable=False,
        )
        batch_op.alter_column(
            'check_name',
            existing_type=sa.VARCHAR(),
            nullable=False,
        )
        batch_op.alter_column(
            'contract_id',
            existing_type=sa.INTEGER(),
            nullable=False,
        )
    with op.batch_alter_table('guideline_sections') as batch_op:
        if _has_unique_constraint('guideline_sections', 'uq_guideline_section_framework_key'):
            batch_op.drop_constraint('uq_guideline_section_framework_key', type_='unique')
        batch_op.create_index(op.f('uq_guideline_section_framework_key'), ['framework_id', 'section_key'], unique=True)
        batch_op.create_index(
            op.f('ix_guideline_sections_framework_id'),
            ['framework_id'],
            unique=False
        )
        batch_op.create_index(op.f('ix_guideline_sections_id'), ['id'], unique=False)
    _create_guideline_views()
    # ### end Alembic commands ###
