"""Add field_type and value to SignatureField

Revision ID: 467b1594dac6
Revises: b191e6dd1433
Create Date: 2026-03-10 17:27:52.427570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467b1594dac6'
down_revision: Union[str, Sequence[str], None] = 'b191e6dd1433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signature_fields', sa.Column('field_type', sa.String(), nullable=True))
    op.add_column('signature_fields', sa.Column('value', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signature_fields', 'value')
    op.drop_column('signature_fields', 'field_type')
    # ### end Alembic commands ###
