"""Add signed_file_path to Contract

Revision ID: 5c7380fda72c
Revises: c4affc73be00
Create Date: 2026-03-10 16:08:52.653087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c7380fda72c'
down_revision: Union[str, Sequence[str], None] = 'c4affc73be00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('signed_file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'signed_file_path')
    # ### end Alembic commands ###
