"""Add scale to SignatureField

Revision ID: 6f1c9779b214
Revises: 197a44ca9125
Create Date: 2026-03-10 17:21:05.694699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1c9779b214'
down_revision: Union[str, Sequence[str], None] = '197a44ca9125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signature_fields', sa.Column('scale', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signature_fields', 'scale')
    # ### end Alembic commands ###
