"""add document drive tables

Revision ID: 7c2d9f4a8b10
Revises: 16c8f62c96ae
Create Date: 2026-03-29 23:00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '7c2d9f4a8b10'
down_revision: Union[str, Sequence[str], None] = '16c8f62c96ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    if not inspect(conn).has_table('document_drives'):
        op.create_table(
            'document_drives',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
    drives_indexes = {row["name"] for row in inspect(conn).get_indexes('document_drives')}
    if 'ix_document_drives_id' not in drives_indexes:
        op.create_index(op.f('ix_document_drives_id'), 'document_drives', ['id'], unique=False)

    if not inspect(conn).has_table('document_drive_folders'):
        op.create_table(
            'document_drive_folders',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('drive_id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['drive_id'], ['document_drives.id']),
            sa.PrimaryKeyConstraint('id')
        )
    folders_indexes = {row["name"] for row in inspect(conn).get_indexes('document_drive_folders')}
    if 'ix_document_drive_folders_id' not in folders_indexes:
        op.create_index(op.f('ix_document_drive_folders_id'), 'document_drive_folders', ['id'], unique=False)

    if not inspect(conn).has_table('document_drive_files'):
        op.create_table(
            'document_drive_files',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('folder_id', sa.Integer(), nullable=False),
            sa.Column('original_filename', sa.String(), nullable=False),
            sa.Column('filename', sa.String(), nullable=False),
            sa.Column('content_type', sa.String(), nullable=True),
            sa.Column('size_bytes', sa.Integer(), nullable=True),
            sa.Column('upload_id', sa.String(), nullable=False),
            sa.Column('file_path', sa.String(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['folder_id'], ['document_drive_folders.id']),
            sa.PrimaryKeyConstraint('id')
        )
    files_indexes = {row["name"] for row in inspect(conn).get_indexes('document_drive_files')}
    if 'ix_document_drive_files_id' not in files_indexes:
        op.create_index(op.f('ix_document_drive_files_id'), 'document_drive_files', ['id'], unique=False)
    if 'ix_document_drive_files_upload_id' not in files_indexes:
        op.create_index(op.f('ix_document_drive_files_upload_id'), 'document_drive_files', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS document_drive_files")
    op.execute("DROP TABLE IF EXISTS document_drive_folders")
    op.execute("DROP TABLE IF EXISTS document_drives")
    # ### end Alembic commands ###
