"""initialize

Revision ID: b3b7f95b8128
Revises: 
Create Date: 2026-03-18 16:33:03.568897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b7f95b8128'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _index_exists(conn, insp, name: str) -> bool:
    try:
        for idx in insp.get_indexes('contracts'):
            if idx.get('name') == name:
                return True
    except Exception:
        pass
    return False


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy import inspect
    conn = op.get_bind()
    insp = inspect(conn)
    # lost_and_found is a sqlite corruption artifact; drop only if it exists
    if insp.has_table('lost_and_found'):
        op.drop_table('lost_and_found')

    # All operations below only apply when patching a pre-existing database.
    # On a clean restore the other migration branch creates all tables from
    # scratch, so we skip gracefully if the tables are not yet present.
    if not insp.has_table('contracts'):
        return

    if not _index_exists(conn, insp, 'ix_contracts_contract_number'):
        op.create_index(op.f('ix_contracts_contract_number'), 'contracts', ['contract_number'], unique=True)

    # SQLite requires batch_alter_table for column changes
    if insp.has_table('document_versions'):
        with op.batch_alter_table('document_versions') as batch_op:
            batch_op.alter_column('is_latest', nullable=True, existing_type=sa.BOOLEAN())
    if insp.has_table('master_signers'):
        with op.batch_alter_table('master_signers') as batch_op:
            batch_op.alter_column('is_active', nullable=True, existing_type=sa.BOOLEAN())
    if insp.has_table('signature_fields'):
        with op.batch_alter_table('signature_fields') as batch_op:
            batch_op.create_foreign_key('fk_sig_versionsigner', 'version_signers', ['version_signer_id'], ['id'])
            batch_op.create_foreign_key('fk_sig_docversion', 'document_versions', ['version_id'], ['id'])
    if insp.has_table('templates'):
        with op.batch_alter_table('templates') as batch_op:
            batch_op.alter_column('is_active', nullable=True, existing_type=sa.BOOLEAN())
    if insp.has_table('version_signers'):
        with op.batch_alter_table('version_signers') as batch_op:
            batch_op.alter_column('version_id', nullable=True, existing_type=sa.INTEGER())
            batch_op.alter_column('master_signer_id', nullable=True, existing_type=sa.INTEGER())
            batch_op.alter_column('signing_order', nullable=True, existing_type=sa.INTEGER())
            batch_op.alter_column('status', nullable=True, existing_type=sa.VARCHAR())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('version_signers', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('version_signers', 'signing_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('version_signers', 'master_signer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('version_signers', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.drop_constraint(None, 'signature_fields', type_='foreignkey')
    op.drop_constraint(None, 'signature_fields', type_='foreignkey')
    op.alter_column('master_signers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('document_versions', 'is_latest',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('ix_contracts_contract_number'), table_name='contracts')
    op.create_table('lost_and_found',
    sa.Column('rootpgno', sa.INTEGER(), nullable=True),
    sa.Column('pgno', sa.INTEGER(), nullable=True),
    sa.Column('nfield', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('c0', sa.NullType(), nullable=True),
    sa.Column('c1', sa.NullType(), nullable=True),
    sa.Column('c2', sa.NullType(), nullable=True),
    sa.Column('c3', sa.NullType(), nullable=True),
    sa.Column('c4', sa.NullType(), nullable=True),
    sa.Column('c5', sa.NullType(), nullable=True),
    sa.Column('c6', sa.NullType(), nullable=True),
    sa.Column('c7', sa.NullType(), nullable=True),
    sa.Column('c8', sa.NullType(), nullable=True),
    sa.Column('c9', sa.NullType(), nullable=True),
    sa.Column('c10', sa.NullType(), nullable=True),
    sa.Column('c11', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
