"""Add signers and signature fields

Revision ID: be4fa38babe0
Revises: 3799a4e31c7d
Create Date: 2026-03-10 15:40:05.523951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be4fa38babe0'
down_revision: Union[str, Sequence[str], None] = '3799a4e31c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signers_email'), 'signers', ['email'], unique=False)
    op.create_index(op.f('ix_signers_id'), 'signers', ['id'], unique=False)
    op.create_table('signature_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('signer_id', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('x_pos', sa.Float(), nullable=True),
    sa.Column('y_pos', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('is_signed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['signer_id'], ['signers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signature_fields_id'), 'signature_fields', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signature_fields_id'), table_name='signature_fields')
    op.drop_table('signature_fields')
    op.drop_index(op.f('ix_signers_id'), table_name='signers')
    op.drop_index(op.f('ix_signers_email'), table_name='signers')
    op.drop_table('signers')
    # ### end Alembic commands ###
