"""Initial migration

Revision ID: d45e906adcea
Revises: 
Create Date: 2026-03-10 15:03:38.364732

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'd45e906adcea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(bind, table_name: str, column_name: str) -> bool:
    return any(
        c["name"] == column_name
        for c in inspect(bind).get_columns(table_name)
    )


def upgrade() -> None:
    """Upgrade schema."""
    # This migration is used as the bootstrap root. In some environments the database
    # can be deleted and rebuilt from scratch, so we guard DDL operations for missing
    # objects to keep it idempotent and resilient.
    bind = op.get_bind()
    inspector = inspect(bind)

    if not inspector.has_table("templates"):
        op.create_table(
            "templates",
            sa.Column("id", sa.Integer(), primary_key=True, index=True),
            sa.Column("name", sa.String(), index=True),
            sa.Column("category", sa.String(), nullable=True),
            sa.Column("content", sa.Text(), nullable=True),
            sa.Column("version", sa.Integer(), default=1),
            sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("1")),
            sa.Column("created_at", sa.DateTime(), default=datetime.utcnow),
        )

    if not inspector.has_table("contracts"):
        op.create_table(
            "contracts",
            sa.Column("id", sa.Integer(), primary_key=True, index=True),
            sa.Column("contract_number", sa.String(), unique=True, index=True, nullable=True),
            sa.Column("title", sa.String(), index=True, nullable=True),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column("template_id", sa.Integer(), sa.ForeignKey("templates.id"), nullable=True),
            sa.Column("status", sa.String(length=32), nullable=False, server_default=sa.text("'draft'")),
            sa.Column("content", sa.Text(), nullable=True),
            sa.Column("value", sa.Float(), nullable=True),
            sa.Column("start_date", sa.DateTime(), nullable=True),
            sa.Column("end_date", sa.DateTime(), nullable=True),
            sa.Column("created_at", sa.DateTime(), default=datetime.utcnow),
            sa.Column("updated_at", sa.DateTime(), default=datetime.utcnow),
        )

    if not inspector.has_table("compliance_records"):
        op.create_table(
            "compliance_records",
            sa.Column("id", sa.Integer(), primary_key=True, index=True),
            sa.Column("contract_id", sa.Integer(), sa.ForeignKey("contracts.id", ondelete="CASCADE"), nullable=False),
            sa.Column("check_name", sa.String(), nullable=False),
            sa.Column("status", sa.String(), nullable=False),
            sa.Column("findings", sa.Text(), nullable=True),
            sa.Column("created_at", sa.DateTime(), default=datetime.utcnow),
        )

    if not _has_column(bind, "compliance_records", "page_number"):
        op.add_column("compliance_records", sa.Column("page_number", sa.Integer(), nullable=True))
    if not _has_column(bind, "contracts", "file_path"):
        op.add_column("contracts", sa.Column("file_path", sa.String(), nullable=True))
    if not _has_column(bind, "contracts", "file_type"):
        op.add_column("contracts", sa.Column("file_type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'file_type')
    op.drop_column('contracts', 'file_path')
    op.drop_column('compliance_records', 'page_number')
    # ### end Alembic commands ###
